### ISSUE TITLE
"UnBoundLocalError : local variable 'inp'referenced before assignment " while pressing the button in GPIO 18

### ISSUE THREAD

**Issue by SoorajKrishna** [sammachin/AlexaPi#13]
File "main.py", line 135 ,in start
l,data = inp.read()

**Comment by HumbertoL** [comment]
This seems to happen when the button is not connected properly. You get this error when Pin 18 is "floating". Make sure you have it connected correctly to the button. Refer to this diagram to make sure you connected the pins to the correct pins on the button itself.

![](http://www.cs.uregina.ca/Links/class-info/MSI/Buttons/Pictures/pushbutton_schem.png)

**Comment by RamblingGeekUK** [comment]
This also seems to happen if you have the speaker connected to the Audio out of the sound card rather then the jack on the Pi

**Comment by doubledrat** [comment]
I've found it happens if you press the button before "Alexa's ready" :-)

seriously though, when it says "hello", it's not quite ready for input.  In my experience, waiting for about 3-5 secs before pressing the button and you don't get this error

**Comment by sammachin** [comment]
Not sure why it would occur using the sound card output instead of the audio jack, I've tested with both and not had and issue.

@doubledrat is right the Hello does trigger a little early, there's also 3 flashes of the green LED whcih is just after the hello and is the better indication that its ready.

@SoorajKrishna does this happen all the time for you or just occasionally?
