### ISSUE TITLE
AlexaPi on Win7 desktop?

### ISSUE THREAD

**Issue by mrx23dot** [sammachin/AlexaPi#78]
Would it be possible to run AlexaPi on Win7 desktop?
that would be epic!

**Comment by Hoki-gcav** [comment]
Not this version, because windows doesn't support all the libraries involved in making this. At some point some will make Alexa for Windows, but it won't be coded in python.

**Comment by lennysh** [comment]
I have a version written in .Net, but it's not been upgraded to the new API yet...

**Comment by sammachin** [comment]
Not easy to get this up & running on Win7 mainly due to the audio limitations and also the reliance on external GPIO buttons for control.

I have built a browser based version though which is using similar code to version 1.0, you can use it for free at https://alexaweb.herokuapp.com or download and run your own from http://github.com/sammachin/alexaweb

**Comment by lennysh** [comment]
My version uses an on screen button, so mouse required.  Runs fine using VLC on Windows.
